config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#landing_page'
  get 'composing_mode', to: "compositions#composing_mode", as: 'composing_mode'
  get 'compose', to: "compositions#compose", as: 'compose'
  post 'compose', to: "compositions#save_compose", as: 'save_compose'
  #latest is for ajax only
  get 'latest_api', to:"compositions#latest_api", as: 'latest_api'
  get 'index', to: "compositions#index", as: 'index'
  get 'index_all', to: "compositions#index_all", as: 'index_all'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
  get 'home', to: "pages#home", as: 'home'
  get 'minor_2nd', to: "harmonies#minor_2nd", as: 'minor_2nd'
  get 'major_2nd', to: "harmonies#major_2nd", as: 'major_2nd'
  get 'minor_3rd', to: "harmonies#minor_3rd", as: 'minor_3rd'
  get 'major_3rd', to: "harmonies#major_3rd", as: 'major_3rd'
  get 'perfect_4th', to: "harmonies#perfect_4th", as: 'perfect_4th'
  get 'augmented_4th', to: "harmonies#augmented_4th", as: 'augmented_4th'
  get 'perfect_5th', to: "harmonies#perfect_5th", as: 'perfect_5th'
  get 'minor_6th', to: "harmonies#minor_6th", as: 'minor_6th'
  get 'major_6th', to: "harmonies#major_6th", as: 'major_6th'
  get 'minor_7th', to: "harmonies#minor_7th", as: 'minor_7th'
  get 'major_7th', to: "harmonies#major_7th", as: 'major_7th'
  get 'perfect_8ve', to: "harmonies#perfect_8ve", as: 'perfect_8ve'

  get 'major_triad', to: "harmonies#major_triad", as: 'major_triad'
  get 'minor_triad', to: "harmonies#minor_triad", as: 'minor_triad'
  get 'diminished_triad', to: "harmonies#diminished_triad", as: 'diminished_triad'
  get 'augmented_triad', to: "harmonies#augmented_triad", as: 'augmented_triad'
  get 'tritone', to: "harmonies#tritone", as: 'tritone'
  get 'dominant_7th_chord', to:"harmonies#dominant_7th_chord", as: 'dominant_7th_chord'


  # for ajax
  # get 'harmonies/construct_major_triad', to: "harmonies#construct_major_triad"
  # get 'harmonies/construct_tritone', to: "harmonies#construct_tritone"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/theme.rb
class Theme < ApplicationRecord
  # scope
  # usuaully, fetch all themenotes, if don't care, give by id
  # now: give me the array accoding to the rank
  has_many(:theme_notes, -> { order('rank') })
  has_many(:notes, through: :theme_notes)
end

app/models/theme_note.rb
class ThemeNote < ApplicationRecord
  belongs_to(:theme)
  belongs_to(:note)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  # protect_from_forgery with: :null_session
  # because post a bit dangerous, changes database
  # CORS
  skip_before_action :verify_authenticity_token

  def composing_mode
  end

  def compose
  end

  def save_compose
    theme = Theme.create(name: "Theme #{Theme.count + 1}")
    p params[:my_theme]
    # above gives an array of note names e,g, [C3,E3,G3], from key.dataset.note;
    # change to array of note instances e.g [#< name:'C3'...>, #< name:'E3'...>, #<name: 'G3'>]
    @my_note_sequence = params[:my_theme].map{ |note| Note.find_by_name(note) }
    @my_note_sequence.each_with_index do |note, i|
      ThemeNote.create(note: note, rank: i + 1, theme: theme)
    end
    # save to database: theme_1 by storing all the theme notes in sequence
    # to retrieve: SELECT * FROM theme_notes WHERE theme_id = 1 ORDER BY rank;
    # returns eventually,[C3, E3, G3]
    # render json: @my_note_sequence
  end


  def latest_api
    unless Theme.last.nil?
      @newest = Theme.last.notes
      render json: @newest
    else
      render json: {}
    end
  end

  def index
    # @all_themes = Theme.all.map { |theme| theme.notes }
    # render json: @all_themes
  end

  def index_all
    @themes = Theme.all
  end

end

app/controllers/harmonies_controller.rb
class HarmoniesController < ApplicationController

  # intervals
  def minor_2nd
  end

  def major_2nd
  end

  def minor_3rd
  end

  def major_3rd
  end

  def perfect_4th
  end

  def augmented_4th
  end

  def perfect_5th
  end

  def minor_6th
  end

  def major_6th
  end

  def minor_7th
  end

  def major_7th
  end

  def perfect_8ve
  end

  # chords
  def major_triad
  end

  def minor_triad
  end

  def diminished_triad
  end

  def augmented_triad
  end

  def tritone
  end

  def dominant_7th_chord
  end

end

  # def construct_major_triad
  #   @notes = Note.all
  #   @root = params[:number].to_i
  #   @results = [Note.find_by_number(@root), Note.find_by_number(@root + 4),Note.find_by_number(@root + 7)]
  #   render json: @results
  # end

  # def construct_tritone
  #   @notes = Note.all
  #   @root = params[:number].to_i
  #   @results = [Note.find_by_number(@root), Note.find_by_number(@root + 6)]
  #   render json: @results
  # end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end


  def landing_page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/compositions/compose.html.erb
<script aync src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div id="right-half">
    <div class="box-pink">
      <div class="welcoming-words">
        👋 👋 👋 <br>
        ✨ Feeling like composing ✨<br>
      </div>
      <button class="btn-unicorn" id="start-save">Start to store</button>
      <button class="btn-unicorn" id='restart'>Restart</button>
      <button class="btn-unicorn" id='done'>I am done!</button>
    </div>
    <div class="my-record"></div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/compositions/composing_mode.html.erb
<script aync src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div id="right-half">
    <div class="box-pink">
      <div class="welcoming-words">
        👋 👋 👋 <br>
        ✨ Feeling like composing ✨<br>
      </div>
      <button class="btn-unicorn"><%= link_to "Compose a theme", compose_path %></button>
      <button class="btn-unicorn"><%= link_to "Hear my themes", index_path %></button>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/compositions/index.html.erb
<script aync src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div id="right-half">
    <div class="box-pink">
      <div class="welcoming-words">
        👋 👋 👋<br>
        ✨ Hear your themes: ✨<br>
      </div>
      <div id="ting">
        Let's hear your <em>latest</em> theme 🎵:<br>
        <button id="ting-btn">PLAY</button>
      </div>

   <!--    <div class="choice-btn">
        <%= link_to "Or, view all your themes 🙌:", index_all_path %>
      </div> -->

    </div>
    <div class="my-record"></div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/compositions/index_all.html.erb
<ol>
  <% @themes.each do |theme| %>
    <li><%= theme %></li>
  <% end %>
</ol>

app/views/harmonies/augmented_triad.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how an augmented triad <br>
          is contructed👇
        </div>
        <div class="show-notes">

        </div>
      </div>
      <div class="right-box">
        <div>
          Augmented triad is often associated with sadness and sorrows.🌂<br>
          Augmented triad is made of a major 3rd and a augmented 5th.<br>

          <br>
          <button type="button" class="modal-btn" data-toggle="modal" data-target="#exampleModal">
            See usage in masterpiece
          </button>
        </div>
      </div>
    </div>
    <div class="display-inversion"></div>
    <%= render 'shared/piano' %>
  </div>
</div>



<!-- Modal -->

<% name = "Augmented Triad!" %>
<% link =  "https://www.youtube.com/watch?v=Ugc5FZsycAw&t=3701s&ab_channel=FelicesCantusBach" %>
<% image_path = "prelude.png" %>
<% image_width = "800px" %>
<% piece = "Pelude in C major, Bach" %>
<%= render 'shared/modal', name: name, link: link, image_path: image_path, piece: piece, image_width: image_width %>

app/views/harmonies/diminished_triad.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how a diminished triad<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
        <div>
          Diminished triad is made of a minor 3rd and a diminished 5th.<br>
          <br>
          <button type="button" class="modal-btn" data-toggle="modal" data-target="#exampleModal">
            See usage in masterpiece
          </button>
        </div>
      </div>
    </div>
    <div class="display-inversion"></div>
    <%= render 'shared/piano' %>
  </div>
</div>



<!-- Modal -->

<% name = "Diminished Triad!" %>
<% link =  "https://www.youtube.com/watch?v=Ugc5FZsycAw&t=3701s&ab_channel=FelicesCantusBach" %>
<% image_path = "prelude.png" %>
<% image_width = "800px" %>
<% piece = "Pelude in C major, Bach" %>
<%= render 'shared/modal', name: name, link: link, image_path: image_path, piece: piece, image_width: image_width %>

app/views/harmonies/dominant_7th_chord.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words" style="padding: 3px">
          Strike a key to <br>
          see how the dominant 7th chord <br>
          is contructed👇
        </div>
        <div class="show-notes">

        </div>
      </div>
      <div class="right-box" style="padding: 3px">
        <div>
          Dominant 7th chord is by far the most common 7th chord used in compositions 🎶<br>
          It’s made of a major 3rd, a perfect 5th, and a minor 7th. Note that the major 3rd and the minor 7th forms a tritone.<br>
          <br>
          <button type="button" class="modal-btn" data-toggle="modal" data-target="#exampleModal">
            See usage in masterpiece
          </button>
        </div>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>




<!-- Modal -->

<% name = "Dominant 7th!" %>
<% link =  "https://www.youtube.com/watch?v=Ugc5FZsycAw&t=3701s&ab_channel=FelicesCantusBach" %>
<% image_path = "prelude.png" %>
<% image_width = "800px" %>
<% piece = "Pelude in C major, Bach" %>
<%= render 'shared/modal', name: name, link: link, image_path: image_path, piece: piece, image_width: image_width %>

app/views/harmonies/major_2nd.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how major 2nd<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
          Major intervals tend to give a brighter feeling.☀️<br>
          It’s made of 2 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/major_3rd.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how major 3rd<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
          Major intervals tend to give a brighter feeling.☀️<br>
          It’s made of 4 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/major_6th.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how major 6th<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
          Major intervals tend to give a brighter feeling.☀️<br>
          It’s made of 9 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/major_7th.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how major 7th <br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
          Major intervals tend to give a brighter feeling.☀️<br>
          It’s made of 11 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/major_triad.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how a major triad<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
        <div>
          Major triad is often associated with brightness and happiness.☀️<br>
          It’s made of a major 3rd and a perfect 5th.<br>
          <br>
          <button type="button" class="modal-btn" data-toggle="modal" data-target="#exampleModal">
            See usage in masterpiece
          </button>
        </div>
      </div>
    </div>
    <div class="display-inversion"></div>
    <%= render 'shared/piano' %>
  </div>
</div>



<!-- Modal -->


<% name = "Major Triad: First Bar!" %>
<% link =  "https://www.youtube.com/watch?v=KB59i99Wxc4&ab_channel=AshishXiangyiKumar" %>
<% image_path = "prelude.png" %>
<% image_width = "800px" %>
<% piece = "See Sir Andras Schiff play Prelude in C Major, Bach" %>
<%= render 'shared/modal', name: name, link: link, image_path: image_path, piece: piece, image_width: image_width %>

app/views/harmonies/minor_2nd.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how minor 2nd<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
          Minor intervals tend to give a sadder feeling.🌧️<br>
          It's made of 1 semitone above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/minor_6th.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how minor 6th<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
          Minor intervals tend to give a sadder feeling.🌧️<br>
          It’s made of 8 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/minor_7th.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how minor 7th<br>
          is contructed👇
        </div>
        <div class="show-notes">

        </div>
      </div>
      <div class="right-box">
          Minor intervals tend to give a sadder feeling.🌧️<br>
          It’s made of 10 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/minor_triad.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how a minor triad<br>
          is contructed👇
        </div>
        <div class="show-notes">
        </div>
      </div>
      <div class="right-box">
        <div>
          Minor triad by comparison has a slight hue of sadness or submission.🔷🔹<br>
          It’s made of a minor 3rd and a perfect 5th.<br>
          <br>
          <button type="button" class="modal-btn" data-toggle="modal" data-target="#exampleModal">
            See usage in masterpiece
          </button>
        </div>
      </div>
    </div>
    <div class="display-inversion"></div>
    <%= render 'shared/piano' %>
  </div>
</div>




<% name = "Minor Triad - Second Bar!" %>
<% link =  "https://www.youtube.com/watch?v=KB59i99Wxc4&ab_channel=AshishXiangyiKumar" %>
<% image_path = "prelude.png" %>
<% image_width = "800px" %>
<% piece = "See Sir Andras Schiff play Prelude in C Major, Bach" %>
<%= render 'shared/modal', name: name, link: link, image_path: image_path, piece: piece, image_width: image_width %>

app/views/harmonies/perfect_8ve.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words">
          Strike a key to <br>
          see how perfect octave <br>
          is contructed👇
        </div>
        <div class="show-notes">

        </div>
      </div>
      <div class="right-box">
          Manor intervals tend to give a brighter feeling.☀️<br>
          It’s made of 12 semitones above the root.<br>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/harmonies/tritone.html.erb
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div class="box">
    <div class="info">
      <div class="left-box">
        <div class="words" style="padding: 0">
          Strike a key to <br>
          see how the tritone<br>
          is contructed👇
        </div>
        <div class="show-notes">

        </div>
      </div>
      <div class="right-box">
        <div>
          Tritone is the 👿 chord with an inherent dissonance. <br> In the Middle Ages, it was referred to as <strong><em >diabolus in musica</em></strong> - the devil in music, and was foridden in compositions.<br>
          It’s made of 3 tones above the root.<br>
          <br>
          <button type="button" class="modal-btn" data-toggle="modal" data-target="#exampleModal">
            See usage in masterpiece
          </button>
        </div>
      </div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>


<!-- Modal -->
<% name = "All tritones!" %>
<% link =  "https://www.youtube.com/watch?v=KB59i99Wxc4&ab_channel=AshishXiangyiKumar" %>
<% image_path = "dante.png" %>
<% image_width = "auto" %>
<%= render 'shared/modal', name: name, link: link, image_path: image_path, piece: "See Mikhail Pletnev play Dante Sonata, Listz", image_width: image_width %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🎹 PortablePiano</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%#= javascript_pack_tag 'hello_erb', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<script aync src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<div class='overall-container'>
  <%= render 'shared/vertical_bar' %>
  <div id="right-half">
    <div class="box-pink">
      <div class="welcoming-words">
        👋 👋 👋 <br>
        ✨ Strike a few notes ✨<br>
        Or, choose a chord/interval on the left<br>
      </div>
      <button class="btn-unicorn" id="compose-btn"><%= link_to "Compose", composing_mode_path %></button>
      <div class="show-notes"></div>
    </div>
    <%= render 'shared/piano' %>
  </div>
</div>

app/views/pages/landing_page.html.erb
<%= render 'shared/navbar' %>

<div id='below-navbar'>
  <div id='left-block'>
	<div id="titile-big">Composer's <br>
	Portable Piano</div>
	<div id='title-small'>Get inspired anytime, anywhere</div>
    <button class="btn-unicorn">
      <%= link_to "Play Now", home_path %>
    </button>
  </div>
  <%= image_tag 'landing-page-pic.png', alt: "landing-page-pic", id: "landing-page-pic"%>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <%= image_tag image_path, alt: "logo", style: "height:120%;width: #{image_width};" %>
        <div class="pieces">
          <a class="music-link" href="<%= link %>" target="_blank"><%= piece %></a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn modal-btn" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-light bg-white">
  <%= image_tag 'logo.png', alt: "logo", class: "logo-pic"%>
  <ul class="login-links">
    <li class="pink-btn">Create user</li>
    <li class="pink-btn">login</li>
  </ul>
</nav>

app/views/shared/_piano.html.erb
<div class="piano">
  <div data-note="C3" data-number="1" class="key white">
    <p class="whitekey-word">q</p>
  </div>
  <div data-note="Db3" data-number="2" class="key black">
    <p class="blackkey-word">2</p>
  </div>
  <div data-note="D3" data-number="3" class="key white">
    <p class="whitekey-word">w</p>
  </div>
  <div data-note="Eb3" data-number="4" class="key black">
    <p class="blackkey-word">3</p>
  </div>
  <div data-note="E3" data-number="5" class="key white">
    <p class="whitekey-word">e</p>
  </div>
  <div data-note="F3" data-number="6" class="key white">
    <p class="whitekey-word">r</p>
  </div>
  <div data-note="Gb3" data-number="7" class="key black">
    <p class="blackkey-word">5</p>
  </div>
  <div data-note="G3" data-number="8" class="key white">
    <p class="whitekey-word">t</p>
  </div>
  <div data-note="Ab3" data-number="9" class="key black">
    <p class="blackkey-word">6</p>
  </div>
  <div data-note="A3" data-number="10" class="key white">
    <p class="whitekey-word">y</p>
  </div>
  <div data-note="Bb3" data-number="11" class="key black">
    <p class="blackkey-word">7</p>
  </div>
  <div data-note="B3" data-number="12" class="key white">
    <p class="whitekey-word">u</p>
  </div>
  <div data-note="C4" data-number="13" class="key white">
    <p class="whitekey-word">i</p>
  </div>
  <div data-note="Db4" data-number="14" class="key black">
    <p class="blackkey-word">9</p>
  </div>
  <div data-note="D4" data-number="15" class="key white">
    <p class="whitekey-word">o</p>
  </div>
  <div data-note="Eb4" data-number="16" class="key black">
    <p class="blackkey-word">0</p>
  </div>
  <div data-note="E4" data-number="17" class="key white">
    <p class="whitekey-word">p</p>
  </div>
  <div data-note="F4" data-number="18" class="key white">
    <p class="whitekey-word">z</p>
  </div>
  <div data-note="Gb4" data-number="19" class="key black">
    <p class="blackkey-word">s</p>
  </div>
  <div data-note="G4" data-number="20" class="key white">
    <p class="whitekey-word">x</p>
  </div>
  <div data-note="Ab4" data-number="21" class="key black">
    <p class="blackkey-word">d</p>
  </div>
  <div data-note="A4" data-number="22" class="key white">
    <p class="whitekey-word">c</p>
  </div>
  <div data-note="Bb4" data-number="23" class="key black">
    <p class="blackkey-word">f</p>
  </div>
  <div data-note="B4" data-number="24" class="key white">
    <p class="whitekey-word">v</p>
  </div>
  <div data-note="C5" data-number="25" class="key white">
    <p class="whitekey-word">b</p>
  </div>
</div>

app/views/shared/_vertical_bar.html.erb
<div class="vertical-bar">

  <button class="btn-unicorn">
    <%= link_to "Home", home_path %>
  </button>

  <div class="scroll">

    <div class="choice-btn" id="minor_2nd">
      <%= link_to "minor 2nd", minor_2nd_path %>
    </div>
    <div class="choice-btn" id="major_2nd">
      <%= link_to "major 2nd", major_2nd_path %>
    </div>
    <div class="choice-btn" id="minor_3rd">
      <%= link_to "minor 3rd", minor_3rd_path %>
    </div>
    <div class="choice-btn" id="major_3rd">
      <%= link_to "major 3rd", major_3rd_path %>
    </div>
    <div class="choice-btn" id="perfect_4th">
      <%= link_to "perfect 4th", perfect_4th_path %>
    </div>
    <div class="choice-btn" id="augmented_4th">
      <%= link_to "augmented 4th", augmented_4th_path %>
    </div>
    <div class="choice-btn" id="perfect_5th">
      <%= link_to "perfect 5th", perfect_5th_path %>
    </div>
    <div class="choice-btn" id="minor_6th">
      <%= link_to "minor 6th", minor_6th_path %>
    </div>
    <div class="choice-btn" id="major_6th">
      <%= link_to "major 6th", major_6th_path %>
    </div>
    <div class="choice-btn" id="minor_7th" >
      <%= link_to "minor 7th", minor_7th_path %>
    </div>
    <div class="choice-btn" id="major_7th">
      <%= link_to "major 7th", major_7th_path %>
    </div>
    <div class="choice-btn" id="perfect_8ve">
      <%= link_to "perfect 8ve", perfect_8ve_path %>
    </div>

    <div class="choice-btn" id="major_triad">
      <%= link_to "major triad", major_triad_path %>
    </div>
      <div class="choice-btn" id="minor_triad">
      <%= link_to "minor triad", minor_triad_path %>
    </div>
      <div class="choice-btn" id="diminished_triad">
      <%= link_to "diminished triad", diminished_triad_path %>
    </div>
      <div class="choice-btn" id="augmented_triad">
      <%= link_to "augmented triad", augmented_triad_path %>
    </div>
    <div class="choice-btn" id="tritone">
      <%= link_to "tritone", tritone_path %>
    </div>
    <div class="choice-btn" id="dominant_7th_chord">
      <%= link_to "dominant 7th chord", dominant_7th_chord_path %>
    </div>
  </div>

</div>